# Generated by Django 3.2.4 on 2021-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210623_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('random_thoughts', 'Random_thoughts'), ('carrer', 'Carrer'), ('travel', 'Travel'), ('business', 'Business'), ('life', 'Life')], default='life', max_length=25),
        ),
    ]
